# Generated by Django 4.2.15 on 2024-08-25 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Seller',
        ),
    ]
