# Generated by Django 4.2.15 on 2024-08-29 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0003_customer_alter_seller_city_alter_seller_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=10)),
                ('length', models.IntegerField(max_length=5)),
                ('filling', models.IntegerField(max_length=4)),
                ('metal_shel', models.IntegerField(max_length=3)),
                ('weight', models.IntegerField(max_length=4)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wms_app.customer')),
            ],
        ),
    ]
