# Generated by Django 4.2.15 on 2024-08-29 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0004_coil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coil',
            name='filling',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(1500)]),
        ),
        migrations.AlterField(
            model_name='coil',
            name='length',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(7000)]),
        ),
        migrations.AlterField(
            model_name='coil',
            name='metal_shel',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AlterField(
            model_name='coil',
            name='weight',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3000)]),
        ),
    ]
