# Generated by Django 4.2.15 on 2024-08-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0005_alter_coil_filling_alter_coil_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coil',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wms_app.customer'),
        ),
    ]
