# Generated by Django 4.2.15 on 2024-08-31 15:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0007_alter_coil_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=50)),
                ('current_balance', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10000000)])),
                ('weight_of_lot', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(40000)])),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wms_app.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Calcium',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wms_app.material')),
            ],
            options={
                'verbose_name_plural': 'Calcium',
            },
            bases=('wms_app.material',),
        ),
        migrations.CreateModel(
            name='CalciumSilicon',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wms_app.material')),
            ],
            options={
                'verbose_name_plural': 'CalciumSilicon',
            },
            bases=('wms_app.material',),
        ),
        migrations.CreateModel(
            name='Carbon',
            fields=[
                ('material_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wms_app.material')),
                ('carbon_p', models.FloatField(verbose_name=django.core.validators.MaxValueValidator(100.0))),
                ('sulfur_p', models.FloatField(verbose_name=django.core.validators.MaxValueValidator(100.0))),
            ],
            bases=('wms_app.material',),
        ),
    ]
