# Generated by Django 4.2.15 on 2024-09-04 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0012_includedmaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calcium',
            options={},
        ),
        migrations.AlterModelOptions(
            name='calciumsilicon',
            options={},
        ),
        migrations.AlterField(
            model_name='coil',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coils', to='wms_app.customer'),
        ),
        migrations.AlterField(
            model_name='coil',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coils', to='wms_app.order'),
        ),
        migrations.AlterField(
            model_name='coil',
            name='type',
            field=models.CharField(choices=[('CK-30', 'CK-30'), ('CK-40', 'CK-40'), ('Ca Si', 'Ca Si'), ('Ca-Fe 30/70', 'Ca-Fe 30/70'), ('Ca-Fe 40/60', 'Ca-Fe 40/60'), ('C', 'C'), ('B', 'B')], default='CK-30', max_length=12),
        ),
        migrations.AlterField(
            model_name='material',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='wms_app.seller'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='wms_app.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('CK-30', 'CK-30'), ('CK-40', 'CK-40'), ('Ca Si', 'Ca Si'), ('Ca-Fe 30/70', 'Ca-Fe 30/70'), ('Ca-Fe 40/60', 'Ca-Fe 40/60'), ('C', 'C'), ('B', 'B')], default='CK-30', max_length=12),
        ),
    ]
