# Generated by Django 4.2.15 on 2024-09-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms_app', '0014_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quality_certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
    ]
